version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: nuclio
      MONGO_INITDB_ROOT_PASSWORD: chatter
      MONGO_DATABASE_NAME: nuclio-chatter
    ports:
      - "27025:27017"
